# https://decapcms.org/docs/backends-overview/
backend:
  name: git-gateway # adds users without giving them direct write access to your GitHub or GitLab repository.
  branch: main # default: master
  cms_label_prefix: decap-cms # default: netlify-cms/
  # Options:
  # name: github/gitlab/bitbucket # all users added must have push access to your content repository.
  # repo: owner-name/repo-name # Path to your GitHub repository

# https://decapcms.org/docs/configuration-options/
publish_mode: editorial_workflow
display_url: https://vuedn.netlify.app/
media_folder: "docs/.vuepress/public/media" # Media files will be stored in the repo under docs/.vuepress/public/media
public_folder: "/media" # The src attribute for uploaded media will begin with /media
editor:
  preview: false # disabled markdown preview in CMS
collections:
  - name: "notes"
    label: "Medical Notes"
    label_singular: "Note"
    folder: "docs/notes"
    create: true
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Last Updated", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Body", name: "body", widget: "markdown" }